version: "3"

services:
  runner:
    build:
      context: ${PWD}
      dockerfile: scripts/integration/Dockerfile
      args:
        - RUST_VERSION=${RUST_VERSION}
    working_dir: /code
    command:
      - "cargo"
      - "nextest"
      - "run"
      - "--no-fail-fast"
      - "--no-default-features"
      - "--features"
      - "datadog-logs-integration-tests"
      - "--lib"
      - "::datadog::logs::"
    environment:
      - TEST_DATADOG_API_KEY
    volumes:
      - ${PWD}:/code
      - target:/code/target
      - cargogit:/usr/local/cargo/git
      - cargoregistry:/usr/local/cargo/registry

volumes:
  target: {}
  cargogit: {}
  cargoregistry: {}
